sudo: true
dist: xenial
services:
  - docker
language: python
python:
  - '3.7'
before_install:
  - "pip install 'lander>=0.1.0,<0.2'"
script:
  # Compile PDF using containerized lsst-texmf
  - "docker run --rm -v `pwd`:/workspace -w /workspace lsstsqre/lsst-texmf:latest sh -c 'make'"
  # Deploy website. See https://github.com/lsst-sqre/lander for CLI options
  - "lander --upload --pdf TSTN-001.pdf --lsstdoc TSTN-001.tex --env=travis --ltd-product tstn-001"
env:
  global:
    - secure: "X1NLOscBGKI4KQB43LKE/V/lDCvYh21ZtqrVVHwjsojH0zTRoLE/VX/s5iFx+vjWyS5BBc58xjoRZZfbBdggeceXS2p65Rt9/i9zE9bqN3ITN9qsvylaY3MFQMHe+ruvow3DMOzv7oED8aU+V68ozNwhkV7m+sqjxmkKgiL8sHbASApShG/86vgnAsa8zk5hHhDc8LlyM8xnjvEwHfQEsFKFys+ccTu4qve7Eet1rEZgiFIyLJvAfXFC/3j2rAYyrCK5+0oWGmVHM+idhZnmVDjOG/7ZvW5uUM3r8bqxxkSCwDxxJb1pc/QKdywaCh/WUnF7S1CYkHkiDeVGwu77pJ9MOEdPi0AwujYhb9jXMF7KVqu16g2wt0y/hbOm+joBbaHRjixRGlunoUQaQ9WOQENZXZ78scpvRqsleSGqE6amKAb3OacOT7OHKfgNz9n2pCeGJBGsFLQmgoHHFk3ow0E+lWBS4C/jr8L5aLtbpgDGvgdmXNUheoMaxwL7j9yaR1wrcUa9jIaOeWT2PpP2WQRWAQI9UxBiVBmLtILHcq9lGVdqYrrWzmTP21it7eYcpKNVyOqetYn3Tin17W7K+69fKvvVA27rdVXiRy1rkbiJwCe6wF1S1iIBJc5veRB/KWBiZOhRAZqnUttPXj26g62XNkJXzWE+9Fstg79ViMg="
    - secure: "s0xW61W77EPuqDU2JmExhKVWYT374+ZgZepdthkPnLlOrDVVrPz5B7sHg44NtQJKMoi+cr7GUnEJfBjZk2aD36JJyz15eOwTgbBOIUDam7DfIdk+qmCx4jxToIU16txOrgGeworpwPp/it15yCJ02biYlMBqz2kf2ygs9vbVclcqP4yS65lBtZ+JWwH+rLgjCg4Qi7jSq6NH3qJN4IwzK0I6xBBi9p+cu6M/D+4w9zPwPFsSj4fIv1ti1JvDqviBoa5V4rvlFZhBcjJaEmqDplRIoWWTQ26/QAmwA+Wf6wUpu0eFxgnga+YWFr2v1a4QATK40a4eluArHI3ZuXxw3xoA1cl45qvtEqq3ImWoVn3khiIYLlHiN9kQIGQY8jJvJNKSGxig2FXTRGqgMd/goKAFMAR+Hi5xaWbbkHiGFdLESLzGMStRckdH5AIoj1LYZGiRus8EdJrziZZ0dZVUUS1VfxL22tZOTkweOQ3aoMowYtLx7dfCBacVnpcih13Ry/hsXKBq7P6Uu4W0WCMp7Sa9jHekN7RB6/HvEdjPEfkfsbKO+T9XbFC/J4R0+eC9xfN+CFehLJ/R6IHuSPrNQSE8/3rlj0UL5XhC5O+3RuhPBvbcYtJDb0n5IejlWOgftF+3ytLYAW/3zOSHHeefIOeOXA5QTfB9PIvSB5yJnWM="
